console.log("dynamic module");

const lorem = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus, aut ab veniam dignissimos possimus similique aliquam obcaecati quia voluptatum est, natus, vel temporibus voluptate dolor a eaque dolores unde quam.
Vitae ipsum natus laudantium aperiam, tempore quae quod magni quo assumenda soluta perferendis minima similique accusantium inventore provident ea aspernatur saepe dicta sequi consectetur! Aperiam expedita odit corrupti dolor animi.
Provident nostrum eius fuga cumque fugit cum veritatis nesciunt laudantium deleniti animi sint, enim voluptatibus repellendus ullam ipsam iusto incidunt. Blanditiis illo similique ab placeat voluptatum beatae a quos vero.
Ab aperiam dolores consectetur magnam similique at quibusdam. Et unde laboriosam non odio doloremque! Atque libero doloremque accusamus quibusdam voluptatem magnam cupiditate aut, officiis aliquam minima at culpa. Veritatis, quibusdam.
Inventore iste consequuntur corporis sapiente maiores sunt, repellendus doloribus nesciunt consequatur est odit in dolor itaque aliquam? Nam vero maxime eaque obcaecati, in sunt ut placeat, cupiditate aperiam voluptate suscipit.
Vitae, molestias quae aperiam quisquam ea saepe illo, necessitatibus ullam, incidunt sapiente aliquid. Sunt quam inventore maiores harum voluptas impedit perferendis laboriosam modi ipsam rerum, aliquid alias nulla, ex unde.
Omnis, quas. Excepturi optio, ad sint consequatur harum laudantium quia omnis sunt dolorem. Omnis ea nobis ex sed dolore possimus accusantium nemo, ipsum voluptatibus, nisi eaque non doloribus neque voluptatum!
A eaque iure placeat, iusto porro corporis sint natus repellat molestiae veniam maxime omnis repellendus explicabo alias in rem corrupti harum at. Eaque dolor amet odio minus laudantium voluptates corporis!
Ullam sequi tempora cumque fuga esse blanditiis quae autem eum. Tempore enim placeat assumenda ipsa provident, ut, vero tempora illo maxime dicta quam eligendi vel obcaecati rem, neque sint quo?
Fuga neque optio impedit aperiam eius est odit, sint ratione veniam porro ullam, quia facilis eos nemo iste reiciendis velit alias hic nesciunt suscipit fugiat! Possimus facilis et reiciendis beatae.
Voluptatum, iusto maxime. Culpa eius non blanditiis, autem inventore et dolor ullam eaque quia possimus. In, eveniet, numquam, nisi voluptates aliquid aut architecto deleniti mollitia quod soluta eos reprehenderit hic.
Aliquam, minima praesentium nihil quod facere voluptatum nobis est veritatis non voluptates laborum similique hic vel sunt nisi architecto sapiente laboriosam aut dignissimos distinctio nam consectetur illum itaque asperiores. Accusantium.
Eveniet, nesciunt veniam. Et architecto iure omnis obcaecati optio similique recusandae ullam delectus dolorum nesciunt explicabo praesentium, repellendus ex doloribus perspiciatis eligendi totam, corrupti, ut odio placeat nisi nulla. Mollitia.
Consectetur ipsum delectus consequuntur assumenda? Illum ea accusantium corrupti illo labore voluptatibus cupiditate saepe quidem eum perspiciatis quia repellat debitis minima optio, facilis, voluptas vero laboriosam, delectus reiciendis laudantium expedita.
Consequuntur, facilis minus in porro eligendi natus harum quis sequi ratione odio beatae rem quaerat nobis, quidem sed. Maiores sit asperiores ipsam vero natus earum saepe accusamus quis autem nulla.
Accusantium totam officiis maxime repellat exercitationem cum, nam amet facere quaerat? Ut aperiam tempora libero eligendi inventore repudiandae? Consequatur esse dolorem molestias temporibus repellat officia mollitia sequi facilis illum sed!
Illum distinctio magni voluptates, quo similique, aliquid reiciendis tempora recusandae rerum aspernatur possimus dignissimos saepe aliquam voluptate laboriosam et iure veniam nobis, illo quod repellendus consequatur! Velit corrupti incidunt reiciendis!
Quos dolore repellendus cumque officia eligendi cupiditate quidem id, ipsam inventore consequuntur. Nam ullam modi consequuntur non eum quod qui similique expedita. Id suscipit, minima eligendi dolore dicta iusto deleniti?
Nulla praesentium natus aperiam sint quisquam incidunt nobis, id saepe facere laboriosam accusantium commodi eos hic quis consectetur dolorum laudantium dicta dolores ad repudiandae? Dolorum vitae aspernatur tenetur molestiae esse.
Ipsum consequatur rem dicta maxime, reprehenderit aspernatur asperiores accusantium aliquid voluptatibus? Cum officia ut, officiis quam adipisci quia numquam aspernatur suscipit nisi. Labore voluptatibus molestiae ut quaerat, distinctio laboriosam laudantium?`;